Portfolio_Project/Controllers/PortfolioController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using Microsoft.AspNetCore.Mvc;

namespace Portfolio_Project.Controllers
{
    public class PortfolioController : Controller
    {
        PortfolioManager portfolioManager = new PortfolioManager(new EfPortfolioDal());
        public IActionResult Index()
        {
            var values = portfolioManager.TGetList();
            return View(values);
        }
        [HttpGet]
        public IActionResult AddPortfolio()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddPortfolio(Portfolio p)
        {
            PortfolioValidator validations = new PortfolioValidator();
            ValidationResult results = validations.Validate(p);
            if (results.IsValid)
            {
                portfolioManager.TAdd(p);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
        public IActionResult DeletePortfolio(int id)
        {
            var values = portfolioManager.TGetById(id);
            portfolioManager.TDelete(values);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult EditPortfolio(int id)
        {
            var values = portfolioManager.TGetById(id);
            return View(values);
        }
        [HttpPost]
        public IActionResult EditPortfolio(Portfolio portfolio)
        {
            PortfolioValidator validations = new PortfolioValidator();
            ValidationResult results = validations.Validate(portfolio);
            if (results.IsValid)
            {
                portfolioManager.TUptade(portfolio);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in results.Errors) 
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
    }
}

Portfolio_Project/Views/Portfolio/AddPortfolio.cshtml
@model EntityLayer.Concrete.Portfolio
@{
    ViewData["Title"] = "AddPortfolio";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

<div class="card-header border-0">
    <h3 class="mb-0">Proje Ekleme Sayfası</h3>
</div>
@using (Html.BeginForm("AddPortfolio", "Portfolio", FormMethod.Post))
{
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <p class="card-description"> Yeni Proje Ekleme Paneli </p>
                <form class="forms-sample">
                    <br />
                    @Html.Label("Proje Başlığı")
                    @Html.TextBoxFor(x => x.Name, new { @class = "form-control"})
                    @Html.ValidationMessageFor(x=>x.Name)
                    <br />
                    <label>Görsel 1</label>
                    @Html.TextBoxFor(x => x.ImageUrl, new { @class = "form-control"})
                    @Html.ValidationMessageFor(x => x.ImageUrl)
                    <br />
                    <label>Görsel 2</label>
                    @Html.TextBoxFor(x => x.ImageUrl2, new { @class = "form-control"})
                    @Html.ValidationMessageFor(x => x.ImageUrl2)
                    <br />
                    <label>Proje URL</label>
                    @Html.TextBoxFor(x => x.ProjectUrl, new { @class = "form-control"})
                    @Html.ValidationMessageFor(x => x.ProjectUrl)
                    <br />
                    <label>Fiyat</label>
                    @Html.TextBoxFor(x => x.Price, new { @class = "form-control"})
                    @Html.ValidationMessageFor(x => x.Price)
                    <br />
                    <label>Tamamlanma Oranı</label>
                    @Html.TextBoxFor(x => x.Value, new { @class = "form-control"})
                    @Html.ValidationMessageFor(x => x.Value)
                    <br />
                    <label>Proje URL</label>
                    @Html.TextBoxFor(x => x.ProjectUrl, new { @class = "form-control"})
                    @Html.ValidationMessageFor(x => x.ProjectUrl)
                    <br />
                    <label>Proje URL</label>
                    @Html.TextBoxFor(x => x.ProjectUrl, new { @class = "form-control"})
                    @Html.ValidationMessageFor(x => x.ProjectUrl)
                    <br />
                    <button class="btn btn-info">Kaydet</button>

                </form>
            </div>
        </div>
    </div>
}

Portfolio_Project/Views/Portfolio/EditPortfolio.cshtml
@model EntityLayer.Concrete.Portfolio
@{
    ViewData["Title"] = "EditPortfolio";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

<div class="card-header border-0">
    <h3 class="mb-0">Proje Düzenleme Sayfası</h3>
</div>
@using (Html.BeginForm("EditPortfolio", "Portfolio", FormMethod.Post))
{
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <p class="card-description"> Proje Düzenleme Paneli </p>
                <form class="forms-sample">
                    @Html.HiddenFor(x =>x.PortfolioID)
                    <br />
                    @Html.Label("Proje Başlığı")
                    @Html.TextBoxFor(x => x.Name, new { @class = "form-control"})
                    @Html.ValidationMessageFor(x=>x.Name)
                    <br />
                    <label>Görsel 1</label>
                    @Html.TextBoxFor(x => x.ImageUrl, new { @class = "form-control"})
                    @Html.ValidationMessageFor(x => x.ImageUrl)
                    <br />
                    <label>Görsel 2</label>
                    @Html.TextBoxFor(x => x.ImageUrl2, new { @class = "form-control"})
                    @Html.ValidationMessageFor(x => x.ImageUrl2)
                    <br />
                    <label>Proje URL</label>
                    @Html.TextBoxFor(x => x.ProjectUrl, new { @class = "form-control"})
                    @Html.ValidationMessageFor(x => x.ProjectUrl)
                    <br />
                    <label>Fiyat</label>
                    @Html.TextBoxFor(x => x.Price, new { @class = "form-control"})
                    @Html.ValidationMessageFor(x => x.Price)
                    <br />
                    <label>Tamamlanma Oranı</label>
                    @Html.TextBoxFor(x => x.Value, new { @class = "form-control"})
                    @Html.ValidationMessageFor(x => x.Value)
                    <br />
                    <label>Platform</label>
                    @Html.TextBoxFor(x => x.Platform, new { @class = "form-control"})
                    @Html.ValidationMessageFor(x => x.Platform)
                    <br />
                    <button class="btn btn-info">Düzenle</button>
                </form>
            </div>
        </div>
    </div>
}

Portfolio_Project/Views/Portfolio/Index.cshtml
@using EntityLayer.Concrete
@model List<Portfolio>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

<div class="row">
    <div class="col">
        <div class="card bg-default shadow">
            <div class="card-header bg-transparent border-0">
                <h3 class="text-white mb-0">Projelerim</h3>
            </div>
            <div class="table-responsive">
                <table class="table align-items-center table-dark table-flush">
                    <thead class="thead-white">
                        <tr>
                            <th scope="col" class="sort" data-sort="name">Proje</th>
                            <th scope="col" class="sort" data-sort="budget">Ücret</th>
                            <th scope="col" class="sort" data-sort="status">Durum</th>
                            <th scope="col">Görseller</th>
                            <th scope="col" class="sort" data-sort="completion">Tamamlanma Oranı</th>
                            <th scope="col">Sil</th>
                            <th scope="col">Düzenle</th>
                        </tr>
                    </thead>
                    <tbody class="list">
                        @foreach (var item in Model)
                        {
                            <tr>
                                <th scope="row">
                                    <div class="media align-items-center">
                                        <a href="#" class="avatar rounded-circle mr-3">
                                            <img alt="Image placeholder" src="@item.Platform">
                                        </a>
                                        <div class="media-body">
                                            <span class="name mb-0 text-sm">@item.Name</span>
                                        </div>
                                    </div>
                                </th>
                                <td class="budget">
                                    @item.Price
                                </td>
                                <td>
                                    <span class="badge badge-dot mr-4">
                                        <i class="bg-success"></i>
                                        <span class="status">Tamamlandı</span>
                                    </span>
                                </td>
                                <td>
                                    <div class="avatar-group">
                                        <a href="#" class="avatar avatar-sm rounded-circle" data-toggle="tooltip" data-original-title="Ryan Tompson">
                                            <img alt="Image placeholder" src="~/argon-dashboard-master/assets/img/theme/team-1.jpg">
                                        </a>
                                        <a href="#" class="avatar avatar-sm rounded-circle" data-toggle="tooltip" data-original-title="Romina Hadid">
                                            <img alt="Image placeholder" src="~/argon-dashboard-master/assets/img/theme/team-2.jpg">
                                        </a>
                                        <a href="#" class="avatar avatar-sm rounded-circle" data-toggle="tooltip" data-original-title="Alexander Smith">
                                            <img alt="Image placeholder" src="~/argon-dashboard-master/assets/img/theme/team-3.jpg">
                                        </a>
                                        <a href="#" class="avatar avatar-sm rounded-circle" data-toggle="tooltip" data-original-title="Jessica Doe">
                                            <img alt="Image placeholder" src="~/argon-dashboard-master/assets/img/theme/team-4.jpg">
                                        </a>
                                    </div>
                                </td>
                                <td>
                                    <div class="d-flex align-items-center">
                                        <span class="completion mr-2">@item.Value%</span>
                                        <div>
                                            <div class="progress">
                                                <div class="progress-bar bg-warning" role="progressbar" aria-valuenow="@item.Value" aria-valuemin="0" aria-valuemax="100" style="width: @item.Value%;"></div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                                <td><a href="/Portfolio/DeletePortfolio/@item.PortfolioID" class="btn btn-danger">Sil</a></td>
                                <td><a href="/Portfolio/EditPortfolio/@item.PortfolioID" class="btn btn-outline-warning">Düzenle</a></td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<br />
<a href="/Portfolio/AddPortfolio/" class="btn btn-success">Yeni Proje Girişi</a>