Portfolio_Project/Controllers/SkillController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace Portfolio_Project.Controllers
{
    public class SkillController : Controller
    {
        SkillManager skillManager = new SkillManager(new EfSkillDal());

        public IActionResult Index()
        {
            var values = skillManager.TGetList();
            return View(values);
        }
        [HttpGet]
        public IActionResult AddSkill()
        {

            return View();
        }
        [HttpPost]
        public IActionResult AddSkill(Skill skill)
        {
            skillManager.TAdd(skill);
            return RedirectToAction("Index");
        }
        public IActionResult DeleteSkill(int id)
        {
            var values = skillManager.TGetById(id);
            skillManager.TDelete(values);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult EditSkill(int id)
        {
            var values = skillManager.TGetById(id);
            return View(values);

        }
        [HttpPost]
        public IActionResult EditSkill(Skill skill)
        {
            skillManager.TUptade(skill);
            return RedirectToAction("Index");
        }
    }
}

Portfolio_Project/Views/Skill/AddSkill.cshtml
@model EntityLayer.Concrete.Skill
@{
    ViewData["Title"] = "AddSkill";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <p class="card-description"> Yeni Yetenek Ekleme Paneli </p>
            <form class="forms-sample" method="post">
                <div class="form-group">
                    <label>Başlık</label>
                    @Html.TextBoxFor(x=>x.Title, new{ @class = "form-control"})
                </div>
                <div class="form-group">
                    <label>Değer</label>
                    @Html.TextBoxFor(x=>x.Value, new{ @class = "form-control"})
                </div>
                <button type="submit" class="btn btn-warning mr-2">Kaydet</button>
                <button class="btn btn-primary">İptal</button>
            </form>
        </div>
    </div>
</div>

Portfolio_Project/Views/Skill/EditSkill.cshtml
@model EntityLayer.Concrete.Skill


@{
    ViewData["Title"] = "EditSkill";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

<div class="card-header border-0">
    <h3 class="mb-0">Yetenek Düzenleme Sayfası</h3>
</div>
@using (Html.BeginForm("EditSkill", "Skill", FormMethod.Post))
{
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <p class="card-description"> Yetenek Düzenleme Paneli </p>
                <form class="forms-sample">
                    <div class="form-group">
                        <label>ID</label>
                        @Html.TextBoxFor(x=>x.SkillID, new{ @class = "form-control"})
                    </div>
                    <div class="form-group">
                        <label>Başlık</label>
                        @Html.TextBoxFor(x=>x.Title, new{ @class = "form-control"})
                    </div>
                    <div class="form-group">
                        <label>Değer</label>
                        @Html.TextBoxFor(x=>x.Value, new{ @class = "form-control"})
                    </div>
                    <button type="submit" class="btn btn-warning mr-2">Kaydet</button>
                    <button class="btn btn-primary">İptal</button>
                </form>
            </div>
        </div>
    </div>
}

Portfolio_Project/Views/Skill/Index.cshtml
@using EntityLayer.Concrete
@model List<Skill>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}


<div class="row">
    <div class="col">
        <div class="card bg-default shadow">
            <div class="card-header bg-transparent border-0">
                <h3 class="text-white mb-0">Yeteneklerim</h3>
                <!-- Light table -->
                <div class="table-responsive">
                    <table class="table align-items-center table-flush">
                        <thead class="thead-light">
                            <tr>
                                <th scope="col" class="sort" data-sort="name">#</th>
                                <th scope="col" class="sort" data-sort="budget">Başlık</th>
                                <th scope="col" class="sort" data-sort="status">Oran</th>
                                <th scope="col">Sil</th>
                                <th scope="col" class="sort" data-sort="completion">Düzenle</th>
                                <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody class="list">

                            @foreach (var item in Model)
                            {
                                <tr>
                                    <th>
                                        @item.SkillID
                                    </th>
                                    <td class="budget">
                                        @item.Title
                                    </td>
                                    <td>
                                        <div class="d-flex align-items-center">
                                            <span class="completion mr-2">@item.Value %</span>
                                            <div>
                                                <div class="progress">
                                                    <div class="progress-bar bg-success" role="progressbar" aria-valuenow="@item.Value" aria-valuemin="0" aria-valuemax="100" style="width: @item.Value%;"></div>
                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                    <td><a href="/Skill/DeleteSkill/@item.SkillID" class="btn btn-danger">Sil</a></td>
                                    <td><a href="/Skill/EditSkill/@item.SkillID" class="btn btn-success">Güncelle</a></td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    <a href="/Skill/AddSkill/" class="btn btn-primary">Yeni Yetenek Ekle</a>
                </div>
            </div>
        </div>
    </div>
</div>
@*  <script src="~/corona-free-dark-bootstrap-admin-template-1.0.0/template/assets/vendors/js/vendor.bundle.base.js"></script>
*@