Portfolio_Project/Controllers/TestimonialController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace Portfolio_Project.Controllers
{
    public class TestimonialController : Controller
    {
        TestimonialManager testimonialManager = new TestimonialManager(new EfTestimonialDal());
        public IActionResult Index()
        {
            var values = testimonialManager.TGetList();
            return View(values);
        }
        public IActionResult DeleteTestimonial(int id)
        {
            var values = testimonialManager.TGetById(id);
            testimonialManager.TDelete(values);
            return RedirectToAction("Index");
        }
        
        [HttpGet]
        public IActionResult EditTestimonial(int id)
        {
            var values = testimonialManager.TGetById(id);
            return View(values);

        }
        [HttpPost]
        public IActionResult EditTestimonial(Testimonial testimonial)
        {
            testimonialManager.TUptade(testimonial);
            return RedirectToAction("Index");
        }
    }
}

Portfolio_Project/Views/Testimonial/EditTestimonial.cshtml
@model EntityLayer.Concrete.Testimonial


@{
    ViewData["Title"] = "EditSkill";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

<div class="card-header border-0">
    <h3 class="mb-0">Referans Düzenleme Sayfası</h3>
</div>
@using (Html.BeginForm("EditTestimonial", "Testimonial", FormMethod.Post))
{
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <p class="card-description"> Referans Düzenleme Paneli </p>
                <form class="forms-sample">
                    <div class="form-group">
                        <label>ID</label>
                        @Html.TextBoxFor(x=>x.TestimonialID, new{ @class = "form-control"})
                    </div>
                    <div class="form-group">
                        <label>Ad Soyad</label>
                        @Html.TextBoxFor(x=>x.ClientName, new{ @class = "form-control"})
                    </div>
                    <div class="form-group">
                        <label>Şirket</label>
                        @Html.TextBoxFor(x=>x.Company, new{ @class = "form-control"})
                    </div>
                    <div class="form-group">
                        <label>Başlık</label>
                        @Html.TextBoxFor(x=>x.Title, new{ @class = "form-control"})
                    </div>
                    <div class="form-group">
                        <label>Görsel Yolu</label>
                        @Html.TextBoxFor(x=>x.ImageUrl, new{ @class = "form-control"})
                    </div>
                    <div class="form-group">
                        <label>Yorum</label>
                        @Html.TextAreaFor(x=>x.Comment,8,3, new{ @class = "form-control"})
                    </div>
                    <button type="submit" class="btn btn-warning mr-2">Kaydet</button>
                    <button class="btn btn-primary">İptal</button>
                </form>
            </div>
        </div>
    </div>
}

Portfolio_Project/Views/Testimonial/Index.cshtml
@using EntityLayer.Concrete
@model List<Testimonial>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

<div class="row ">
    <div class="col-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Referans Listesi</h4>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th> # </th>
                                <th> Ad Soyad </th>
                                <th> Şirket </th>
                                <th> Unvan </th>
                                <th> Sil </th>
                                <th> Detaylar </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        <img src="@item.ImageUrl" alt="image" />
                                    </td>
                                    <td> @item.ClientName </td>
                                    <td> @item.Company </td>
                                    <td> @item.Title </td>
                                    <td> <a href="/Testimonial/DeleteTestimonial/@item.TestimonialID" class="btn btn-outline-danger">Sil</a></td>
                                    <td> <a href="/Testimonial/EditTestimonial/@item.TestimonialID" class="btn btn-outline-success">Detaylar</a></td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>